In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
type(mylist)

list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
mylist

[1, 2, 3]

In [8]:
myarr = np.array(mylist)

In [9]:
myarr

array([1, 2, 3])

In [10]:
type(myarr)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)      #NumPy has already this idea that this is two dimensional. 
                         #There are three rows by three columns, this is the key idea of NumPy.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3,13,2)       #This is equivalent to the range function in Python.

array([ 3,  5,  7,  9, 11])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((2,5))  #First number is the number of rows and second number is for columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.linspace(0,10,11)   #This command returns how many numbers should be spaced equally in the given range.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [33]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [34]:
len(np.linspace(0,5,21))

21

In [36]:
np.eye(5) #That's the NumPy identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.random.rand(1)

array([0.73805466])

In [45]:
np.random.rand(5,6) # 5 rows, 6 columns. The numbers are between 0 and 1.

array([[0.25862067, 0.58497207, 0.47703195, 0.62428495, 0.22085671,
        0.76605432],
       [0.94816364, 0.69002883, 0.46696188, 0.68375328, 0.24426503,
        0.18254826],
       [0.30659671, 0.41576826, 0.98149927, 0.29363123, 0.76668738,
        0.75917104],
       [0.1658189 , 0.68326995, 0.36123572, 0.73744102, 0.99610235,
        0.97248686],
       [0.47664221, 0.68688456, 0.18767873, 0.80703248, 0.45474503,
        0.28457306]])

In [44]:
np.random.randn(10) #That command says --> give me 10 numbers and they have normal distribution(mean=0, varinace=1)

array([-0.08891054,  1.39712662,  0.27555495,  1.33920707, -0.75410463,
       -1.21457572,  1.07558818, -0.8988365 , -0.07060996, -0.65737727])

In [46]:
np.random.randn(2,3)

array([[ 0.35817891, -0.28809117,  0.29013686],
       [ 0.04589565, -0.60928065,  1.05212002]])

In [49]:
np.random.randint(0,101,5)  # Give me in 0-101 range random 5 numbers.

array([51, 26, 46, 39, 95])

In [50]:
np.random.randint(0,101,(4,5)) # Give me numbers with (4,5) array in that range.

array([[19, 26, 56, 78, 32],
       [ 1, 85, 39, 73, 65],
       [ 8, 98, 53, 64, 88],
       [ 1, 65, 32, 36, 28]])

In [52]:
np.random.randint(0,101,10) # Give me random 10 integers in the range.

array([ 2, 16, 65, 74, 27, 70, 49, 98, 17, 13])

In [57]:
np.random.seed(42) # In a lot of different python libraries 42 is default number.
#The purpose of this command is to assign a given set of random numbers to a value. 
#Thanks to this command, sets of random numbers can be determined, stored and compared with each other.
np.random.rand(4) # 4 numbers between 0 and 1 

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [58]:
np.random.seed(42)
np.random.rand(4)
# As we can see, the numbers are stored

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [60]:
arr = np.arange(25)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
arr.reshape(5,5) #Important point: the number of elements must fit within the number of columns and rows.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
ranarr = np.random.randint(0,101,10)

In [66]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [67]:
ranarr.max()

99

In [68]:
ranarr.min()

2

In [70]:
ranarr.argmax() #This is index location of max number.

5

In [71]:
ranarr.argmin()

7

In [74]:
  ranarr.dtype  # The data type and the number of bits in which the computer stores the data are written.

dtype('int64')

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
arr.shape

(25,)

In [77]:
arr = arr.reshape(5,5)

In [78]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
arr.shape

(5, 5)

In [80]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [81]:
arr1 = np.arange(0,11)

In [82]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr1[8]

8

In [85]:
arr1[1:5]

array([1, 2, 3, 4])

In [88]:
arr1[:5] # is same arr1[0:5]

array([0, 1, 2, 3, 4])

In [89]:
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [99]:
## BROADCASTING !!!!

In [90]:
arr1[0:5] = 100 

In [93]:
arr = np.arange(11)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr[0:5] = 100

In [96]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [98]:
arr = np.arange(0,11)

In [100]:
slice_of_arr = arr[0:5]

In [101]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
slice_of_arr[:] = 99

In [104]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [105]:
arr_copy = arr.copy()

In [106]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [107]:
arr_copy[:] = 100

In [108]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [109]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [112]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])

In [113]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [115]:
arr_2d.shape # Firstly row , column

(4, 3)

In [116]:
arr_2d[0]

array([ 5, 10, 15])

In [119]:
arr_2d[1][1] # to get 25

25

In [121]:
# Also we can use this in same bracket: first one row, second one column.
arr_2d[1,2]   #row 1, column 2

30

In [123]:
arr_2d[:2,1:] #After comma we are talking about columns!

array([[10, 15],
       [25, 30]])

In [124]:
arr = np.arange(1,11)

In [125]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
arr > 4 # Returns back a NumPy array of boolean values.

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [128]:
bool_arr = arr>4

In [129]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [131]:
arr[bool_arr] # Return the values which are greater than 4 

array([ 5,  6,  7,  8,  9, 10])

In [132]:
####### NUMPY OPERATIONS !!!!!!

In [133]:
arr = np.arange(0,10)

In [134]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [136]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [138]:
arr + arr # To do this operation, these arrays have to be the same shape!

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [139]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [140]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [141]:
arr / arr

/var/folders/j4/nj07815j3q9_wz_8g3ghf5r40000gn/T/ipykernel_15441/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [142]:
1 / 0

ZeroDivisionError: division by zero

In [143]:
1 / arr

/var/folders/j4/nj07815j3q9_wz_8g3ghf5r40000gn/T/ipykernel_15441/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [146]:
 # In last three rows, we can see the differences between normal python and NumPy.

In [148]:
np.sqrt(arr) #Square root!

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [149]:
np.sin(arr) # we can do trigonometric functions like sin.

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [151]:
np.log(arr)

/var/folders/j4/nj07815j3q9_wz_8g3ghf5r40000gn/T/ipykernel_15441/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [152]:
#### Some statistical operations :

In [153]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
arr.sum()

45

In [155]:
arr.mean()

4.5

In [157]:
arr.max()

9

In [158]:
arr.min()

0

In [161]:
arr.var() #Variance

8.25

In [162]:
arr.std() #Standard deviation.

2.8722813232690143

In [163]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [166]:
arr2d = np.arange(0,25).reshape(5,5)

In [167]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [168]:
arr2d.shape

(5, 5)

In [170]:
arr2d.sum()

300

In [177]:
arr2d.sum(axis=0) # By setting the axis equal to 0, the columns are summed.

array([50, 55, 60, 65, 70])

In [178]:
arr2d.sum(axis=1) # By setting axis equal to 1, the sum of the rows are summed.

array([ 10,  35,  60,  85, 110])